version: '3.8'

services:
  traffic-monitor:
    build: .
    container_name: traffic_ai_container
    
    ports:
      - "5000:5000"
    
   
    shm_size: '4gb' 
 

    volumes:
      
      - .:/app
      
      - /app/__pycache__

    environment:
      - FLASK_ENV=development
      
      - QT_X11_NO_MITSHM=1

    restart: unless-stopped